### ISSUE TITLE
lack of info about available modes

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/libykneomgr#23]
-m mode 
where are available modes enumerated (their range) with their functions?

i got functionality to what here ? lack of documentation!

**Comment by c3ph3us** [comment]
Does anyone reading this at all?

**Comment by nootrope** [comment]
@c3ph3us type `ykneomgr -h` and note the `-M` option.

**Comment by c3ph3us** [comment]
I will politely ask again...
what are "ALL" avaliable modes with their meaning (their effects)

**Comment by klali** [comment]
updating this seems to have been overlooked. thank you for noticing and I'll push a commit fixing this shortly.

**Comment by klali** [comment]
and that fix is in 590a561ed212956ed963234eec7f733edf597581

**Comment by c3ph3us** [comment]
elaborate please :) 

![neo-modes](https://cloud.githubusercontent.com/assets/10565704/9207853/7008a5d6-4070-11e5-87e3-084b20a60c3f.png)

**Comment by klali** [comment]
so the fix is not released yet, if you look at https://github.com/Yubico/libykneomgr/blob/master/src/cmdline.ggo#L27 you see what the "new" values there will be (mode 6 being composite OTP/U2F/CCID)

**Comment by c3ph3us** [comment]
0 for HID device only,
1 for CCID device only,
81 for CCID device with touch eject,
2 for HID/CCID composite device,
3 for U2F device only,\n4 for OTP/U2F composite device,
5 for U2F/CCID composite device,
6 for OTP/U2F/CCID composite device.

so what about 86 ?

**Comment by klali** [comment]
the 80 (MODE_FLAG_EJECT) only has an effect together with mode 1, so 86 and 6 means the same thing. For early firmwares of the neo 82 and 2 was different in that mode 2 didn't allow OTP from all modes, but this has since been changed into the only behaviour of mode 2.
