### ISSUE TITLE
Github edition key not found

### ISSUE THREAD

**Issue by gregdel** [Yubico/libykneomgr#24]
```
root@desk:~# ykneomgr -V
ykneomgr 0.1.9

root@desk:~# ykneomgr -l
0: Yubico Yubikey 4 CCID 00 00

root@desk:~# ykneomgr -m
error: ykneomgr_discover_match (-2): No device found

root@desk:~# cat /etc/debian_version
8.2
```

The key is in the list but I can't change its mode or get any information.
Any idea ?

**Comment by klali** [comment]
The github branded key is for u2f only. This project only uses the CCID interface of the yubikey.

Though as your key being detected it might have problems. If you do have problems using this key with u2f in chrome please contact Yubico support.
