### ISSUE TITLE
Can not access the device when in Mode 5 - U2F/CCID composite device

### ISSUE THREAD

**Issue by adiroiban** [Yubico/libykneomgr#27]
If the device is set in U2F/CCID composite device from neoman ... or from ykneomgr itself I get

```
$ ykneomgr -m
error: ykneomgr_discover_match (-4): Backend error

```

I have Ubuntu 14.04

```
$ ykneomgr -V
ykneomgr 0.1.8
```

I can change the mode from neoman ... but even if CCID is enabled, neoman will not show the available applets

----------------------

To reproduce set the device in other mode...ex 82

```
$ ykneomgr -m
82
$ ykneomgr -M 5
$ ykneomgr -m
05

# I then eject the device so that it will have the new USB id

$ ykneomgr -m
error: ykneomgr_discover_match (-4): Backend error
```

after device is plugged again the USB id is

```
Bus 002 Device 015: ID 1050:0115 Yubico.com 
```

Thanks!

**Comment by adiroiban** [comment]
Here are the screenshots from neoman for top+ccid and u2f+ccid

![otp_ccid](https://cloud.githubusercontent.com/assets/204609/10998655/51487a9a-849f-11e5-92b9-01104e32b288.png)

![u2f_ccid](https://cloud.githubusercontent.com/assets/204609/10998656/5151cc44-849f-11e5-8c72-956cf016a9ca.png)

```
$ opensc-tool -l
No smart card readers found.
```

I can see the card reader when in otp+ccid mode

**Comment by dainnilsson** [comment]
You almost certainly have an older version of libccid which does not have the latest PIDs for our devices. You can upgrade libccid, or just patch the device list https://github.com/Yubico/yubikey-neo-manager/blob/master/resources/linux-fix-ccid-udev
